lexik_jwt_authentication:
  secret_key: '%env(base64:JWT_SECRET_KEY_BASE64)%'
  public_key: '%env(base64:JWT_PUBLIC_KEY_BASE64)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_ttl: 3600 # 1 hour

  token_extractors:
    # look for a token as Authorization Header
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization
