nelmio_api_doc:
    documentation:
        info:
            title: Spamming App
            description: This is an awesome Spamming App for WSB class!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc.*$) # Accepts routes under /api except /api/doc
