version: '3.4'

services:

  back:
    env_file: .env
    working_dir: /var/www/html/symfony
    build:
      context: ./back
    volumes:
      - ./back:/var/www/html/symfony
      - ./back/.docker/config:/etc/apache2/sites-enabled
    ports:
      - 8080:80

  front:
    env_file: .env
    build:
      context: ./front
      dockerfile: Dockerfile.prod
      target: prod-build
    working_dir: /usr/share/nginx/html
    ports:
      - 80:80

  queue-worker:
    env_file: .env
    image: python:3.9-buster
    working_dir: /home/py
    entrypoint: bash /home/py/entry.bash
    volumes:
      - ./queue:/home/py

  rabbitmq:
    env_file: .env
    image: rabbitmq:management-alpine
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 15672:15672 # web ui

  mongo:
    env_file: .env
    image: mongo:4.2
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  mailhog:
    env_file: .env
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 8025:8025 # web ui

volumes:
  mongo_data: {}
